name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: Bzm-docs/blogs
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: npm install && npm run build && cp google1d4447d38777e3f0.html dist
          BUILD_DIR: dist
          CNAME: https://blogs.bzm.ink
